# Generated by Django 4.1 on 2022-09-02 19:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Html', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Htmlpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('remark', tinymce.models.HTMLField()),
            ],
        ),
    ]
