# Generated by Django 4.1 on 2022-09-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Html', '0002_htmlpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmlpage',
            old_name='remark',
            new_name='page',
        ),
    ]
