# Generated by Django 4.1 on 2022-09-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Html', '0003_rename_remark_htmlpage_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Htmldata',
        ),
    ]
