# Generated by Django 4.1 on 2022-09-03 12:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Html', '0004_delete_htmldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digitalpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('page', tinymce.models.HTMLField()),
            ],
        ),
    ]
