# Generated by Django 4.1 on 2022-09-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Html', '0006_alter_digitalpage_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Htmlpage',
        ),
    ]
