# Generated by Django 4.1 on 2022-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cources',
            name='thumb',
            field=models.ImageField(default='', upload_to='media/cources/'),
        ),
    ]
