# Generated by Django 4.1 on 2022-09-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cources_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cources',
            name='cid',
            field=models.IntegerField(default=110110, max_length=1000),
        ),
    ]
