# Generated by Django 4.1 on 2022-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cources_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cources',
            name='cname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
